### PR TITLE
Knn denoising

### PR DESCRIPTION
**Pull request by ackagel**
Knn denoising plugin.  Need to add a status window/progress bar for long computations, but this should  be good enough for general ui testing.

### CODE REVIEW

**Comment by ackagel** [comment]
just requesting a review on the gamma mixture model EM-solving code above the class declaration.

**Review by ngreenwald — APPROVED** [review]
I don't have anything useful to say about mixture modeling, will defer to @bcollica and @alex-l-kong

**Comment by bcollica** [comment]
@ngreenwald I'm sure it's all correct , but I'm happy to give it a look through.  Although I'm still getting used to the code and structure of everything so it will probably take me longer than normal.  So don't wait up on merging if @alex-l-kong gives it the thumbs up lol.

**Review by bcollica — COMMENTED** [review]
I did a quick profiling of the code, and it looks like most of the time is spent in a lower level call made by gamma.pdf().  Unfortunately this might be unavoidable given the source code of the function/package.  The other main slowdown was happening in _calq_q, specifically in lower level calls within np.sum().  You might be able to improve run time slightly by using base python sum() rather than np.sum().  np.sum() has a lot of numpy specific argument checking that doesn't appear to be relevant to this call specifically, and this became clear when profiling np.sum() against base sum() directly.  

You may also consider combining the two calls to _calc_q for the delta_q calculation into one call within _calc_q.  In other words, if there is a way to simplify the separate expressions into one function that has all necessary arguments, then it would eliminate having to call _calc_q twice.  This may or may not help as much, and the difference may be negligible if changing from np.sum() to sum() improves performance anyway.

I did the profiling locally on my machine with the largest array dimension being 20,000, but I'm not sure how large the dimensions of the arguments typically are when running this in the pipeline, so there may be differences when combining everything together for a real analysis.

Hope this was useful!

**Comment by alex-l-kong** [comment]
@bcollica I'm surprised that `sum` ended up being much faster than `np.sum`. Generally, `np.sum` is far more efficient for `np.arrays` than base `sum`. What order of magnitude of speedup did you see with base `sum`?

**Comment by bcollica** [comment]
@alex-l-kong you seem to be right, I had compared the two methods on a list rather than a numpy array and that's why it was faster.  So basically disregard that suggestion lol.

**Pull request merged**
